#!/bin/bash
clear
N='\033[0m'
R='\033[0;31m'
G='\033[0;32m'
O='\033[0;33m'
  echo -e "
${O}██   ██  █████  ███████ ██   ██  ██████  ██      ██ 
${N}██   ██ ██   ██ ██      ██   ██ ██    ██ ██      ██ 
███████ ███████ ███████ ███████ ██    ██ ██      ██ 
${R}██   ██ ██   ██      ██ ██   ██ ██ ▄▄ ██ ██      ██ 
${O}██   ██ ██   ██ ███████ ██   ██  ██████  ███████ ██

${N}Coded By Krishanu Sharma
${G}Instagram.com/krishanuIND 
${G}Twitter.com/krishanuIND"
echo -e "              |\033[7;37m Indian Cyber Troops ${N}|\n"
echo -e "              |\033[7;32m Multi HashQLi Decrypter ${N}|\n"
echo ""
PS3='root@HashQLi:'
options=( "Single Hash Decrypter" "Multi Hash Decrypter" "MD5 Decrypter With New Api" "Exit"
)
select opt in "${options[@]}"
do
    case $opt in
        "Single Hash Decrypter")
            clear
N='\033[0m'
R='\033[0;31m'
G='\033[0;32m'
O='\033[0;33m'
  echo -e "
${O}██   ██  █████  ███████ ██   ██  ██████  ██      ██ 
${N}██   ██ ██   ██ ██      ██   ██ ██    ██ ██      ██ 
███████ ███████ ███████ ███████ ██    ██ ██      ██ 
${R}██   ██ ██   ██      ██ ██   ██ ██ ▄▄ ██ ██      ██ 
${O}██   ██ ██   ██ ███████ ██   ██  ██████  ███████ ██

${N}Coded By Krishanu Sharma
${G}Instagram.com/krishanuIND 
${G}Twitter.com/krishanuIND"


read -p "[+] Hash: " hash
                 dec=$(curl -s "http://www.nitrxgen.net/md5db/${hash}")
                 if [[ "$dec" = "" ]]
                 then
                   echo -e "${R}Failed Not Found hash${N}"
                 else
                   echo "Result: $dec"
                 fi
            ;;
        "Multi Hash Decrypter")
            clear
N='\033[0m'
R='\033[0;31m'
G='\033[0;32m'
O='\033[0;33m'
  echo -e "
${O}██   ██  █████  ███████ ██   ██  ██████  ██      ██ 
${N}██   ██ ██   ██ ██      ██   ██ ██    ██ ██      ██ 
███████ ███████ ███████ ███████ ██    ██ ██      ██ 
${R}██   ██ ██   ██      ██ ██   ██ ██ ▄▄ ██ ██      ██ 
${O}██   ██ ██   ██ ███████ ██   ██  ██████  ███████ ██

${N}Coded By Krishanu Sharma
${G}Instagram.com/krishanuIND 
${G}Twitter.com/krishanuIND"
echo -e "              |\033[7;37m Indian Cyber Troops ${N}|\n"
echo -e "              |\033[7;32m Multi HashQLi Decrypter ${N}|\n"
                 read -p "[Root@krishanu] list With Md5 Hash Ex:md5.txt  #: " file
                 for hash in `cat $file`
                 do
                 dec=$(curl -A "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0" --max-time $time_out -s "http://www.nitrxgen.net/md5db/${hash}")
                 if [ "$dec" = "" ];then
                    echo "[?] Not Cracked: ${hash} "
                 else [ "$dec" = "[[:punct:][:alnum:]]*" ]
                     echo "$dec" >> cracked-$list.txt
                     echo "[!] Cracked: ${hash} $del $dec"
                 fi
                 done
            ;;
             "MD5 Decrypter With New Api")
            clear
N='\033[0m'
R='\033[0;31m'
G='\033[0;32m'
O='\033[0;33m'
  echo -e "
${O}██   ██  █████  ███████ ██   ██  ██████  ██      ██ 
${N}██   ██ ██   ██ ██      ██   ██ ██    ██ ██      ██ 
███████ ███████ ███████ ███████ ██    ██ ██      ██ 
${R}██   ██ ██   ██      ██ ██   ██ ██ ▄▄ ██ ██      ██ 
${O}██   ██ ██   ██ ███████ ██   ██  ██████  ███████ ██

${N}Coded By Krishanu Sharma
${G}Instagram.com/krishanuIND 
${G}Twitter.com/krishanuIND"
echo -e "              |\033[7;37m Indian Cyber Troops ${N}|\n"
echo -e "              |\033[7;32m MD5 Decrypter With New Api (single) ${N}|\n"
                 read -p "[Root@krishanu] Enter Hash Here  #: " file
                 for hash in `cat $file`
                 do
                 dec=$(curl -A "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0" --max-time $time_out -s "https://md5decrypt.net/Api/api.php?hash=${hash}&hash_type=md5&email=deanna_abshire@proxymail.eu&code=1152464b80a61728")
                 if [ "$dec" = "" ];then
                    echo "[?] Not Cracked: ${hash} "
                 else [ "$dec" = "[[:punct:][:alnum:]]*" ]
                     echo "$dec" >> cracked-$list.txt
                     echo "[!] Cracked: ${hash} $del $dec"
                 fi
                 done
            ;;
            "Exit")
            break
            ;;
            *) echo "invalid option $REPLY";;
            esac
            done
